### ISSUE TITLE
InternalFailure in httpCall example

### ISSUE THREAD

**Issue by adityasharma1912** [esnible/wasm-examples#2]
Hi there,

Thank you for providing these amazing examples to kick-start development with wasm in envoy proxy.
I am trying to replicate what you have mentioned in your httpCall example.
I am able to create the wasm and attach it to my envoy-proxy container, I can even see the logs I added to the wasm code(just to make sure that the wasm is attached and deployed successfully).

But even after creating a service entry for example.com

`kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: example-com
spec:
  hosts:
  - example.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
EOF`

But I am getting the following response while trying the following curl call:
$kubectl exec -ti deploy/httpbin -c istio-proxy -- curl -v http://httpbin.default:8000/status/418

*   Trying 10.110.179.190:8000...
* TCP_NODELAY set
* Connected to httpbin.default (10.110.179.190) port 8000 (#0)
> GET /status/418 HTTP/1.1
> Host: httpbin.default:8000
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 73
< content-type: text/plain
< date: Fri, 13 May 2022 18:00:20 GMT
< server: istio-envoy
< x-envoy-decorator-operation: httpbin.default.svc.cluster.local:8000/*
<
HttpCall::onResponseHeaders() failed http call, wrSec is **InternalFailure**

Can you please help how can I debug this issue?

**Comment by esnible** [comment]
I don't know.  Perhaps Envoy has changed since I worked on this?

Increase the log level of Envoy and see if it logs anything.
See if the binary signature of Wasm for Proxies in Envoy has changed recently?

**Comment by adityasharma1912** [comment]
ok, thank you. 
Can you please explain the significance of this string "outbound|80||example.com"
what is outbound in this? should I keep it like this only or change it to something as per my configurations?

**Comment by esnible** [comment]
`outbound|80||example.com` is the name of a "cluster".  When we use the word "cluster" in Envoy we don't mean a Kubernetes cluster, we mean a bunch of endpoints that represent the same host.

These strings must be unique in Envoy.  For example if you talk to example.com:80 and example.com:443 each might have different Istio configuration.  Istio creates a mangled name that will be unique.

Envoy has an [admin interface](https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/admin).  Open it using `istioctl dashboard envoy`.  Select "clusters".  The string you use should match one of those.

`"outbound|80||example.com`" means "the Envoy data structure that groups outbound traffic to example.com on port 80 without an Istio subset."

**Comment by adityasharma1912** [comment]
@esnible  thank you for your prompt help. I am able to resolve my issue:
Actually, I was missing the DNS resolution config in the service entry.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: example.com
spec:
  hosts:
  - example.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
    resolution: DNS <<<<<<<<<<<<<<<<<<<<<<<
```


It worked now.

Just for putting the information here:
While checking the istio-proxy logs, I found this:
...
...
**original_dst_load_balancer: No downstream connection or no original_dst.**
...
...

And, then this ticket helped me to resolve the issue: https://github.com/istio/istio/issues/7426

Thanks Again.
